# Generated by Django 3.2.12 on 2023-04-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_nasc',
            field=models.DateField(),
        ),
    ]
