# Generated by Django 3.2.12 on 2023-04-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_userartist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('data_nasc', models.DateField()),
            ],
        ),
    ]
