# Generated by Django 3.2.12 on 2023-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usercontr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userartist',
            name='avaliation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userartist',
            name='type',
            field=models.CharField(default='music', max_length=50),
        ),
    ]
