# Generated by Django 3.2.12 on 2023-04-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userartist_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartist',
            name='type',
            field=models.CharField(default='Musico', max_length=50),
        ),
    ]
