# Generated by Django 3.2.12 on 2023-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userartist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userartist',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userartist',
            name='locality',
            field=models.CharField(default='', max_length=50),
        ),
    ]
