# Generated by Django 3.2.12 on 2023-04-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230420_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartist',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
