# Generated by Django 4.1.7 on 2023-04-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userartist_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userartist',
            name='no_avaliations',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
