# Generated by Django 4.1.7 on 2023-04-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userartist_no_avaliations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsToArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('id_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_id', to='api.userartist')),
                ('id_contr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contr_id', to='api.usercontr')),
            ],
        ),
    ]
