# Generated by Django 4.1.7 on 2023-04-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_commentstoartists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartist',
            name='no_avaliations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
