# Generated by Django 4.1.7 on 2023-04-28 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userartist_no_avaliations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('hours', models.TimeField()),
                ('details', models.CharField(max_length=500)),
                ('id_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistsid', to='api.userartist')),
                ('id_contr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratantid', to='api.usercontr')),
            ],
        ),
    ]
