# Generated by Django 4.1.7 on 2023-04-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartist',
            name='no_avaliations',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
