# Generated by Django 4.1.7 on 2023-04-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_usercontr_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userartist',
            name='subtype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
