# Generated by Django 4.2 on 2023-05-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_artiststypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiststypes',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
