# Generated by Django 4.1.7 on 2023-05-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_proposal_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
